exports.seed = function (knex) {
  return knex("citizens")
    .del()
    .then(function () {
      return knex("citizens").insert([
        {
          national_id: "1635109387",
          name: "زياد ماهر زياد فيومي",
          religion: "مسلم",
          email: "zeyadfaiyoumi@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "النزهه/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "4592037154",
          name: "عباده اسماعيل علي جوابره",
          religion: "مسلم",
          email: "obadajawabreh6@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "النزهه/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "8164329087",
          name: "مــالك سميـح عبد الحفيـظ شحـادة",
          religion: "مسلم",
          email: "malek.shehadeh96@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "النزهه/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "5749268130",
          name: "عبدالله فؤاد حسين دبش",
          religion: "مسلم",
          email: "abdullah.dabash99@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "النزهه/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "2870316498",
          name: "آيـة طه حسين الريماوي",
          religion: "مسلم",
          email: "ayaalrimawi406@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "النزهه/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "6325148702",
          name: "ريم نضال سلامه ابو كرش",
          religion: "مسلم",
          email: "eng.reemnedal@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "النزهه/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "1148179138",
          name: "إدوارد علي سامي الزين",
          religion: "شركسي",
          email: "Edward1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "نزهة القويسمه/القويسمه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "3982922675",
          name: "أنزور الحسنات الحسنات العبدالله",
          religion: "شركسي",
          email: "Anzor1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "الزهراء/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "9085144102",
          name: "مايك الطراونة الطراونة الجعبري",
          religion: "شركسي",
          email: "Mike1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "حمزه/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "7174989888",
          name: "إدوارد الفقيه الفقيه الحسين",
          religion: "شركسي",
          email: "Edward2@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "البشائر/الجامعه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "6906327616",
          name: "أنزور فؤاد نور الجندي",
          religion: "شركسي",
          email: "Anzor2@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الحي الشرقي/الجامعه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "8102055000",
          name: "كارين المجالي المجالي العبدالله",
          religion: "شركسي",
          email: "Karen1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الرحمانيه/الجامعه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "7655308212",
          name: "مايك جودت رامي السعيد",
          religion: "شركسي",
          email: "Mike2@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "القادسيه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "2732804342",
          name: "مايك السلايمة السلايمة الجعبري",
          religion: "شركسي",
          email: "Mike3@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "جعفر الطيار/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "9763602687",
          name: "كارين العايد العايد الحسين",
          religion: "شركسي",
          email: "Karen2@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "القادسيه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "2485273807",
          name: "مايك الناصر الناصر العبدالله",
          religion: "شركسي",
          email: "Mike4@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "القادسيه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "4760633483",
          name: "كارين الطراونة الطراونة الجعبري",
          religion: "شركسي",
          email: "Karen3@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "القادسيه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "4748932096",
          name: "هناء السالم السالم الحسين",
          religion: "شركسي",
          email: "Hanaa@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "العامريه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "1406991627",
          name: "كارين الفقيه الفقيه العبدالله",
          religion: "شركسي",
          email: "Karen4@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الظاهريه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "9732422972",
          name: "إدوارد الخطيب الخطيب الجعبري",
          religion: "شركسي",
          email: "Edward3@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "القادسيه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "7978975300",
          name: "زيتونة الجعبري الجعبري الحسين",
          religion: "شركسي",
          email: "Zaytouna1@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الحسين/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "4278883896",
          name: "كارين العبدالله العبدالله الحسين",
          religion: "شركسي",
          email: "Karen5@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "جعفر الطيار/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "5788961262",
          name: "أنزور الرشيد الرشيد الجعبري",
          religion: "شركسي",
          email: "Anzor3@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "القادسيه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "6520719287",
          name: "كارين الناصر الناصر العبدالله",
          religion: "شركسي",
          email: "Karen6@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الجندي/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "4600911396",
          name: "جاك السلايمة السلايمة الحسين",
          religion: "شركسي",
          email: "Jack@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الوسط التجاري/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "1518984293",
          name: "لينا الفقيه الفقيه الجعبري",
          religion: "شركسي",
          email: "Lina1@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "رمزي والمحرقه/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "4665777033",
          name: "أمين الطراونة الطراونة العبدالله",
          religion: "شيشاني",
          email: "Ameen1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "القويسمه/القويسمه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "3852346883",
          name: "عبير السليم السليم الجعبري",
          religion: "شيشاني",
          email: "Abeer1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "جبل النصر/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "8440806961",
          name: "أمين المجالي المجالي الحسين",
          religion: "شيشاني",
          email: "Ameen2@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "القويسمه/القويسمه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "4922524258",
          name: "أمين الحسنات الحسنات العبدالله",
          religion: "شيشاني",
          email: "Ameen3@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "طبربور/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "6034611694",
          name: "سوزان العايد العايد الجعبري",
          religion: "شيشاني",
          email: "Susan@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "الزهراء/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "1775843259",
          name: "نور الناصر الناصر الحسين",
          religion: "شيشاني",
          email: "Noor1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "ميسلون/الجامعه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "2573268166",
          name: "سعيد الطراونة الطراونة الجعبري",
          religion: "شيشاني",
          email: "Saeed1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الصويفيه/وادي السير",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "6160588258",
          name: "نور العبدالله العبدالله الجعبري",
          religion: "شيشاني",
          email: "Noor2@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الامير علي/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "1048699778",
          name: "سعيد السالم السالم العبدالله",
          religion: "شيشاني",
          email: "Saeed2@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "القادسيه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "5650607368",
          name: "سعيد الناصر الناصر الجعبري",
          religion: "شيشاني",
          email: "Saeed3@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الحسين/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "8029584141",
          name: "عبير العايد العايد الحسين",
          religion: "شيشاني",
          email: "Abeer2@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الرشيد/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "1963119928",
          name: "يحيى الفقيه الفقيه العبدالله",
          religion: "شيشاني",
          email: "Yahya1@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "اسكان النقب/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "3780676015",
          name: "دافيد المجالي المجالي الحسين",
          religion: "شيشاني",
          email: "David1@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "اسكان النقب/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "9675553799",
          name: "أمين الطراونة الطراونة الجعبري",
          religion: "شيشاني",
          email: "Ameen4@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "القادسيه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "5320686642",
          name: "عبير السلايمة السلايمة العبدالله",
          religion: "شيشاني",
          email: "Abeer3@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "رمزي والمحرقه/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "6518258652",
          name: "دافيد العبدالله العبدالله الجعبري",
          religion: "شيشاني",
          email: "David2@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الوسط التجاري/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "4801558871",
          name: "زيتونة الحسنات الحسنات العبدالله",
          religion: "مسلم",
          email: "Zaytouna2@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "حمزه/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "6587519738",
          name: "مفيد السالم السالم العبدالله",
          religion: "مسلم",
          email: "Mufeed1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "ميسلون/الجامعه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "8057416538",
          name: "لطيفة المجالي المجالي الحسين",
          religion: "مسلم",
          email: "Lateefa1@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الازرق الجنوبي/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "8313206448",
          name: "يحيى الطراونة الطراونة الجعبري",
          religion: "مسلم",
          email: "Yahya2@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الصويفيه/وادي السير",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "4141337323",
          name: "يحيى الناصر الناصر العبدالله",
          religion: "مسلم",
          email: "Yahya3@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الصويفيه/وادي السير",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "7614908021",
          name: "محمد السلايمة السلايمة الحسين",
          religion: "مسلم",
          email: "Mohammed1@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "القادسيه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "1672159282",
          name: "عمر الجعبري الجعبري العبدالله",
          religion: "مسلم",
          email: "Omar@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الرشيد/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "7304146142",
          name: "لطيفة الخطيب الخطيب الجعبري",
          religion: "مسلم",
          email: "Lateefa2@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "المطار/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "5874595394",
          name: "لينا العبدالله العبدالله الحسين",
          religion: "مسلم",
          email: "Lina2@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "الطيبه وخريبة السوق/القويسمه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "1432408667",
          name: "لطيفة الفقيه الفقيه الجعبري",
          religion: "مسلم",
          email: "Lateefa3@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "طبربور/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "8767704414",
          name: "مفيد الحسنات الحسنات العبدالله",
          religion: "مسلم",
          email: "Mufeed2@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "جبل النصر/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "1103936088",
          name: "لينا السليم السليم الجعبري",
          religion: "مسلم",
          email: "Lina3@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الحي الشرقي/الجامعه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "5231803711",
          name: "زيتونة المجالي المجالي الحسين",
          religion: "مسلم",
          email: "Zaytouna3@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الصويفيه/وادي السير",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "7359678775",
          name: "لينا الرشيد الرشيد العبدالله",
          religion: "مسلم",
          email: "Lina4@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الصويفيه/وادي السير",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "2925890249",
          name: "لطيفة الطراونة الطراونة الجعبري",
          religion: "مسلم",
          email: "Lateefa4@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "جناعه/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "5206113979",
          name: "نور العايد العايد العبدالله",
          religion: "مسلم",
          email: "Noor3@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "طبربور/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "6912933931",
          name: "محمد السالم السالم الجعبري",
          religion: "مسلم",
          email: "Mohammed2@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "طبربور/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "6601866733",
          name: "محمد المجالي المجالي الحسين",
          religion: "مسلم",
          email: "Mohammed3@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "النهاريه/القويسمه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "3429485516",
          name: "محمد العبدالله العبدالله الجعبري",
          religion: "مسلم",
          email: "Mohammed4@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "العال/ناعور",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "8625591090",
          name: "محمد الخطيب الخطيب الحسين",
          religion: "مسلم",
          email: "Mohammed5@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "المناره/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "7291805699",
          name: "هند العبدالله العبدالله الجعبري",
          religion: "مسلم",
          email: "Hind1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "حمزه/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "2565730470",
          name: "خالد الناصر الناصر الحسين",
          religion: "مسلم",
          email: "Khaled@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "طبربور/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "3145841888",
          name: "مريم الفقيه الفقيه العبدالله",
          religion: "مسلم",
          email: "Mariam1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "سحاب/سحاب",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "5944973246",
          name: "نادية السلايمة السلايمة الجعبري",
          religion: "مسلم",
          email: "Nadia@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "طبربور/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "2693885559",
          name: "فاطمة الطراونة الطراونة الحسين",
          religion: "مسلم",
          email: "Fatima@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "سحاب/سحاب",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "1358645139",
          name: "محمد السالم السالم العبدالله",
          religion: "مسلم",
          email: "Mohammed6@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "حمزه/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "4554823512",
          name: "علي المجالي المجالي الحسين",
          religion: "مسلم",
          email: "Ali1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "ابو علندا/القويسمه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "9904934651",
          name: "هند العبدالله العبدالله الجعبري",
          religion: "مسلم",
          email: "Hind2@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "القويسمه/القويسمه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "6359093506",
          name: "ليلى الفقيه الفقيه الحسين",
          religion: "مسلم",
          email: "Layla@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "البشائر/الجامعه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "1929670071",
          name: "محمد الطراونة الطراونة الجعبري",
          religion: "مسلم",
          email: "Mohammed77@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "ميسلون/الجامعه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "7938090046",
          name: "أحمد الناصر الناصر العبدالله",
          religion: "مسلم",
          email: "Ahmed1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الحي الشرقي/الجامعه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "5296790538",
          name: "محمد السلايمة السلايمة الحسين",
          religion: "مسلم",
          email: "Mohammed8@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "جبل عمان/قصبة عمان",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "1391052928",
          name: "علي العايد العايد الجعبري",
          religion: "مسلم",
          email: "Ali2@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الصويفيه/وادي السير",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "5647600082",
          name: "أحمد الحسنات الحسنات العبدالله",
          religion: "مسلم",
          email: "Ahmed2@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الصويفيه/وادي السير",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "3588967808",
          name: "أحمد الجعبري الجعبري الحسين",
          religion: "مسلم",
          email: "Ahmed3@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "العال/ناعور",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "9715466221",
          name: "أحمد العبدالله العبدالله الجعبري",
          religion: "مسلم",
          email: "Ahmed4@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "القادسيه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "4558689860",
          name: "يوسف الرشيد الرشيد الحسين",
          religion: "مسلم",
          email: "Yusuf1@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "القادسيه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "7774266522",
          name: "هند السالم السالم العبدالله",
          religion: "مسلم",
          email: "Hind3@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الامير علي/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "6892007465",
          name: "أحمد العبدالله العبدالله الجعبري",
          religion: "مسلم",
          email: "Ahmed5@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "القادسيه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "4878670695",
          name: "أحمد المجالي المجالي الحسين",
          religion: "مسلم",
          email: "Ahmed6@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الحسين/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "1351724025",
          name: "هند الفقيه الفقيه الجعبري",
          religion: "مسلم",
          email: "Hind4@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "النزهه/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "4267029334",
          name: "مريم العايد العايد العبدالله",
          religion: "مسلم",
          email: "Mariam2@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الامير شاكر/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "8145254084",
          name: "يوسف الطراونة الطراونة الحسين",
          religion: "مسلم",
          email: "Yusuf2@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الوسط التجاري/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "3124960690",
          name: "مها السليم السليم العبدالله",
          religion: "مسلم",
          email: "Maha1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "الزهراء/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "3407552600",
          name: "مها الناصر الناصر الحسين",
          religion: "مسلم",
          email: "Maha2@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "القادسيه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "9225076739",
          name: "مها المجالي المجالي الجعبري",
          religion: "مسلم",
          email: "Maha3@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الصويفيه/وادي السير",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "7867261729",
          name: "مها العبدالله العبدالله الجعبري",
          religion: "مسلم",
          email: "Maha4@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الصويفيه/وادي السير",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "6947718237",
          name: "مها الفقيه الفقيه العبدالله",
          religion: "مسلم",
          email: "Maha5@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "طبربور/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "1796260554",
          name: "ريتا السالم السالم العبدالله",
          religion: "مسيحي",
          email: "Rita@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "حمزه/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "1498475341",
          name: "ماريا العبدالله العبدالله الجعبري",
          religion: "مسيحي",
          email: "Maria33@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "حمزه/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "8348814326",
          name: "إيلي الحسنات الحسنات العبدالله",
          religion: "مسيحي",
          email: "Elie@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "جبل النصر/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "5400869859",
          name: "جوزيف الطراونة الطراونة الجعبري",
          religion: "مسيحي",
          email: "Joseph1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الأولى",
          region: "المناره/ماركا",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "9145808504",
          name: "نيكول المجالي المجالي السالم",
          religion: "مسيحي",
          email: "Nicole1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الحي الشرقي/الجامعه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "7805460626",
          name: "ريمون العايد العايد الحسين",
          religion: "مسيحي",
          email: "Raymond1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الرحمانيه/الجامعه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "3158394695",
          name: "نيكول السلايمة السلايمة الجعبري",
          religion: "مسيحي",
          email: "Nicole2@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الصويفيه/وادي السير",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "1527518504",
          name: "جورج الخطيب الخطيب العبدالله",
          religion: "مسيحي",
          email: "George1@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الصويفيه/وادي السير",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "1816125870",
          name: "جورج الفقيه الفقيه الحسين",
          religion: "مسيحي",
          email: "George2@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الصويفيه/وادي السير",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "7281002623",
          name: "جوزيف الناصر الناصر الجعبري",
          religion: "مسيحي",
          email: "Joseph2@gmail.com",
          governorate: "عمان",
          electoral_district: "الدائرة الثالثة",
          region: "الروضه/ناعور",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "2961866183",
          name: "ماريا العبدالله العبدالله الجعبري",
          religion: "مسيحي",
          email: "Maria41@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "القادسيه/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "أنثى",
          password: "",
        },
        {
          national_id: "9860138856",
          name: "ريمون الحسنات الحسنات العبدالله",
          religion: "مسيحي",
          email: "Raymond2@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "ام جراده/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "7047791674",
          name: "ريمون المجالي المجالي الجعبري",
          religion: "مسيحي",
          email: "Raymond3@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الرشيد/الرصيفه",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "7552330613",
          name: "جوزيف الطراونة الطراونة الحسين",
          religion: "مسيحي",
          email: "Joseph3@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "نصار/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "1986773614",
          name: "جوزيف السلايمة السلايمة العبدالله",
          religion: "مسيحي",
          email: "Joseph4@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "الحرفيين/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
        {
          national_id: "1994479851",
          name: "سامي الجعبري الجعبري العبدالله",
          religion: "مسيحي",
          email: "Sami@gmail.com",
          governorate: "الزرقاء",
          electoral_district: "دائرة الزرقاء",
          region: "النزهه/قصبة الزرقاء",
          is_voted_party: false,
          is_voted_local: false,
          gender: "ذكر",
          password: "",
        },
      ]);
    });
};
// /**
//  * @param { import("knex").Knex } knex
//  * @returns { Promise<void> }
//  */
// exports.seed = async function(knex) {
//   // Deletes ALL existing entries
//   await knex('table_name').del()
//   await knex('table_name').insert([
//     {id: 1, colName: 'rowValue1'},
//     {id: 2, colName: 'rowValue2'},
//     {id: 3, colName: 'rowValue3'}
//   ]);
// };
